### ISSUE TITLE
Image generation consultation

### ISSUE THREAD

**Issue by kuailexiaohunzi** [VassilisCN/RV-VAE#1]
![image](https://github.com/VassilisCN/RV-VAE/assets/145735082/d7a20a52-7134-4762-82b0-e9ade2d92139)
Thank you for your work. I have a question to consult with you. The mean value of image generation in your code is defined between (-2, 2) with an interval of 0.2. How did this come about. If I want to conduct experiments on other datasets, how should I set this mean range？

**Comment by VassilisCN** [comment]
Hi, the code snippet you show above is for generating images in a grid-like visualization, like in the image below. 
![mnist_grid](https://github.com/VassilisCN/RV-VAE/assets/12500264/0cb30033-a480-47d7-88ee-36c53d9ff614)

Therefore, the `torch.arange(-2,2,0.2)` creates samples from the latent space (which can be near that range of (-2, 2)). The interval 0.2 controls the number of images inside the grid (20x20 images for this code).

If you want to be more precise you can search the trained latent space to see the exact range in which you can generate images. You can do this by finding the min and max values of the means that the encoder outputs for each training sample during inference.

**Comment by kuailexiaohunzi** [comment]
> Hi, the code snippet you show above is for generating images in a grid-like visualization, like in the image below. ![mnist_grid](https://private-user-images.githubusercontent.com/12500264/335110944-0cb30033-a480-47d7-88ee-36c53d9ff614.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzgxNDMsIm5iZiI6MTcxNzA3Nzg0MywicGF0aCI6Ii8xMjUwMDI2NC8zMzUxMTA5NDQtMGNiMzAwMzMtYTQ4MC00N2Q3LTg4ZWUtMzZjNTNkOWZmNjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDE0MDQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNWI5MTBhYjY2MjAzMzE5ZDExYTE2ZTQ0MTQ2ZTkwNGRjM2Y3OTA0YTA0ZTM4NGQ3YzZjZmQ1YTk2ZmY4MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qn93ze_QQVlc0Fd-nnzZcKNVdbemsmySpU6sc1ri7uY)
> 
> Therefore, the `torch.arange(-2,2,0.2)` creates samples from the latent space (which can be near that range of (-2, 2)). The interval 0.2 controls the number of images inside the grid (20x20 images for this code).
> 
> If you want to be more precise you can search the trained latent space to see the exact range in which you can generate images. You can do this by finding the min and max values of the means that the encoder outputs for each training sample during inference.

Understood, thank you very much for your reply
